model:
  # type: transformers
  # type: balance_serve
  type: ktransformers

  name: Qwen3-30B-A3B-128K-GGUF
  path: unsloth/Qwen3-30B-A3B-128K-GGUF
  gguf_path: ./Qwen3-30B-A3B-128K-Q5_K_M.gguf

  device: cuda:0
  cache_lens: 8192
  max_new_tokens: 4096

ext:
  cpu_infer: 10

long_context:
  max_seq_len: 128000
  block_size: 128
  local_windows_len: 4096
  second_select_num: 32
  anchor_type: DYNAMIC
  kv_type: FP16
  dense_layer_num: 2
  anchor_num: 1
  preselect_block: True
  head_select_mode: SHARED
  preselect_block_count: 32
  layer_step: 1
  token_step: 

attn:
  page_size: 256
  chunk_size: 256
kvc2:
  gpu_only: true 
  utilization_percentage: 0.99
  cpu_memory_size_GB: 24